"""
Graph schema models for knowledge graph representation.

This module defines the Entity, Relation, and Community models used
in knowledge graph construction and GraphRAG implementation.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class Entity(BaseModel):
    """
    Represents an entity in the knowledge graph.

    Entities are nodes extracted from documents, representing people,
    organizations, locations, concepts, etc.

    Attributes:
        id: Unique entity identifier (e.g., "E_a1b2c3d4")
        name: Entity name/text as it appears or is standardized
        type: Entity type (Person, Organization, Location, Concept, etc.)
        description: LLM-generated or extracted description
        source_chunk_ids: List of chunk IDs where this entity was found
    """
    id: str = Field(..., description="Unique entity identifier")
    name: str = Field(..., description="Entity name")
    type: str = Field(..., description="Entity type (e.g., Person, Organization, Location, Concept)")
    description: str = Field(
        ...,
        description="Entity description generated by LLM or extracted from text"
    )
    source_chunk_ids: List[str] = Field(
        default_factory=list,
        description="IDs of source chunks where this entity was found"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "id": "E_a1b2c3d4",
                "name": "Acme Corporation",
                "type": "Organization",
                "description": "A technology company specializing in software development",
                "source_chunk_ids": ["chunk_001", "chunk_002"]
            }
        }


class Relation(BaseModel):
    """
    Represents a relationship between two entities in the knowledge graph.

    Relations are directed edges connecting entities, representing
    semantic relationships extracted from text.

    Attributes:
        id: Unique relation identifier
        source: Source entity ID (tail of the relationship)
        target: Target entity ID (head of the relationship)
        type: Relationship type (e.g., BELONGS_TO, LOCATED_AT, WORKS_FOR)
        description: Description of the relationship
        weight: Relationship strength or confidence score
        source_chunk_ids: List of chunk IDs where this relation was found
    """
    id: str = Field(..., description="Unique relation identifier")
    source: str = Field(..., description="Source entity ID")
    target: str = Field(..., description="Target entity ID")
    type: str = Field(..., description="Relationship type")
    description: str = Field(
        ...,
        description="Description of the relationship"
    )
    weight: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Relationship strength or confidence score"
    )
    source_chunk_ids: List[str] = Field(
        default_factory=list,
        description="IDs of source chunks where this relation was found"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "id": "R_e5f6g7h8",
                "source": "E_a1b2c3d4",
                "target": "E_i9j0k1l2",
                "type": "LOCATED_AT",
                "description": "Acme Corporation is located in New York",
                "weight": 0.95,
                "source_chunk_ids": ["chunk_001"]
            }
        }


class Community(BaseModel):
    """
    Represents a community (cluster) in the knowledge graph.

    Communities are groups of densely connected entities discovered
    through graph clustering algorithms (Leiden, Louvain). This is
    a key concept in GraphRAG for hierarchical question answering.

    Attributes:
        community_id: Unique community identifier
        level: Clustering hierarchy level (for hierarchical clustering)
        title: Generated title for the community
        summary: Community-level summary for global questions
        entity_ids: List of entity IDs in this community
        source_chunk_ids: List of chunk IDs that contributed to this community
    """
    community_id: str = Field(..., description="Unique community identifier")
    level: int = Field(
        ...,
        ge=0,
        description="Clustering hierarchy level (0 = base level)"
    )
    title: str = Field(
        default="",
        description="Generated title for the community"
    )
    summary: str = Field(
        ...,
        description="Community summary for global question answering"
    )
    entity_ids: List[str] = Field(
        ...,
        description="List of entity IDs belonging to this community"
    )
    source_chunk_ids: List[str] = Field(
        default_factory=list,
        description="IDs of source chunks contributing to this community"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional community metadata (size, density, etc.)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "community_id": "C_m1n2o3p4",
                "level": 0,
                "title": "Technology Companies in Silicon Valley",
                "summary": "A community of technology companies and their employees located in the San Francisco Bay Area...",
                "entity_ids": ["E_a1b2c3d4", "E_e5f6g7h8", "E_i9j0k1l2"],
                "source_chunk_ids": ["chunk_001", "chunk_002", "chunk_003"],
                "metadata": {
                    "size": 15,
                    "density": 0.75,
                    "modularity": 0.82
                }
            }
        }

    @property
    def size(self) -> int:
        """Number of entities in this community."""
        return len(self.entity_ids)
